modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="mocap"
version="1.1"
displayName="Motion Capture Mod (mocap)"
logoFile="logo.png"
authors="mt1006 (mt1006x)"
credits="Thanks to khitahi for making mod icon"
description="Allows you to record and replay player movements"

[[dependencies.mocap]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mocap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
